import '../models/truck.dart';
import '../models/agent_step.dart';
import '../models/incident.dart';

class DemoData {
  static List<Truck> getInitialTrucks() {
    return [
      Truck(
        truckId: 'TRK-001',
        driverName: 'Ahmed Raza',
        cargoType: 'Vaccines',
        currentTemp: 3.2,
        thresholdTemp: 8.0,
        status: 'Active',
        origin: 'Karachi',
        destination: 'Lahore',
      ),
      Truck(
        truckId: 'TRK-002',
        driverName: 'Bilal Hassan',
        cargoType: 'Dairy',
        currentTemp: 4.1,
        thresholdTemp: 5.0,
        status: 'Active',
        origin: 'Lahore',
        destination: 'Islamabad',
      ),
      Truck(
        truckId: 'TRK-003',
        driverName: 'Usman Khan',
        cargoType: 'Meat',
        currentTemp: 2.8,
        thresholdTemp: 4.0,
        status: 'Active',
        origin: 'Islamabad',
        destination: 'Peshawar',
      ),
      Truck(
        truckId: 'TRK-004',
        driverName: 'Tariq Mahmood',
        cargoType: 'Vaccines',
        currentTemp: 3.5,
        thresholdTemp: 8.0,
        status: 'Active',
        origin: 'Peshawar',
        destination: 'Quetta',
      ),
      Truck(
        truckId: 'TRK-005',
        driverName: 'Fatima Malik',
        cargoType: 'Dairy',
        currentTemp: 3.9,
        thresholdTemp: 5.0,
        status: 'Active',
        origin: 'Quetta',
        destination: 'Multan',
      ),
      Truck(
        truckId: 'TRK-006',
        driverName: 'Omar Sheikh',
        cargoType: 'Meat',
        currentTemp: 2.5,
        thresholdTemp: 4.0,
        status: 'Active',
        origin: 'Multan',
        destination: 'Faisalabad',
      ),
      Truck(
        truckId: 'TRK-007',
        driverName: 'Zara Ahmed',
        cargoType: 'Vaccines',
        currentTemp: 4.2,
        thresholdTemp: 8.0,
        status: 'Active',
        origin: 'Faisalabad',
        destination: 'Karachi',
      ),
      Truck(
        truckId: 'TRK-008',
        driverName: 'Hassan Ali',
        cargoType: 'Dairy',
        currentTemp: 3.6,
        thresholdTemp: 5.0,
        status: 'Active',
        origin: 'Lahore',
        destination: 'Multan',
      ),
      Truck(
        truckId: 'TRK-009',
        driverName: 'Sana Mirza',
        cargoType: 'Meat',
        currentTemp: 2.0,
        thresholdTemp: 4.0,
        status: 'Active',
        origin: 'Karachi',
        destination: 'Islamabad',
      ),
      Truck(
        truckId: 'TRK-010',
        driverName: 'Imran Qureshi',
        cargoType: 'Vaccines',
        currentTemp: 4.0,
        thresholdTemp: 8.0,
        status: 'Active',
        origin: 'Islamabad',
        destination: 'Lahore',
      ),
    ];
  }

  static Truck getBreachedTruck004() {
    return Truck(
      truckId: 'TRK-004',
      driverName: 'Tariq Mahmood',
      cargoType: 'Vaccines',
      currentTemp: 12.5,
      thresholdTemp: 8.0,
      status: 'breach',
      origin: 'Peshawar',
      destination: 'Quetta',
    );
  }

  static Truck getBreachedTruck007() {
    return Truck(
      truckId: 'TRK-007',
      driverName: 'Zara Ahmed',
      cargoType: 'Vaccines',
      currentTemp: 11.0,
      thresholdTemp: 8.0,
      status: 'breach',
      origin: 'Faisalabad',
      destination: 'Karachi',
    );
  }

  static final List<AgentStep> agentTrace = [
    AgentStep(
      step: 'Sensor Monitoring',
      agentName: 'SensorMonitor Agent',
      status: 'DONE',
      output: 'Truck: TRK-004\nTemp: 12.5°C detected\nThreshold exceeded by 4.5°C\nCargo: Vaccines',
      timestamp: '10:38:12 PM',
    ),
    AgentStep(
      step: 'Root Cause Analysis',
      agentName: 'Analysis Agent',
      status: 'DONE',
      output: 'Reasoning: Refrigeration unit compressor failed due to high external ambient temperature.\nConfidence: 95%\nRisk: Vaccine spoilage within 45 minutes.\nCargo: OPV Polio Vaccines (HealthFirst Distributors)',
      timestamp: '10:38:18 PM',
    ),
    AgentStep(
      step: 'Decision Making',
      agentName: 'Decision Agent',
      status: 'DONE',
      output: 'Action: Reroute truck immediately to Lady Reading Hospital Pharmacy Cold Storage.\nAlternative: Dispatch mobile refrigerated backup unit.\nPriority: CRITICAL',
      timestamp: '10:38:24 PM',
    ),
    AgentStep(
      step: 'Execution',
      agentName: 'Execution Agent',
      status: 'DONE',
      output: 'Driver Tariq Mahmood notified via SMS.\nNew route to Lady Reading Hospital Pharmacy activated (ETA: 12 mins).\nReplacement order REP-4091 generated for backup vaccines.',
      timestamp: '10:38:30 PM',
    ),
  ];

  static final List<Incident> incidentHistory = [
    Incident(
      incidentId: 'INC-20260518-001',
      truckId: 'TRK-004',
      cargoType: 'Vaccines',
      breachTemp: 12.5,
      severity: 'CRITICAL',
      pipelineStart: '10:38:12 PM',
      pipelineEnd: '10:38:30 PM',
      totalDuration: 1.8,
      finalOutcome: 'CONTAINED',
      timestamp: 'May 18, 10:38 PM',
    ),
    Incident(
      incidentId: 'INC-20260517-003',
      truckId: 'TRK-007',
      cargoType: 'Vaccines',
      breachTemp: 11.0,
      severity: 'MEDIUM',
      pipelineStart: '03:12:45 PM',
      pipelineEnd: '03:13:02 PM',
      totalDuration: 2.1,
      finalOutcome: 'CONTAINED',
      timestamp: 'May 17, 03:12 PM',
    ),
    Incident(
      incidentId: 'INC-20260516-002',
      truckId: 'TRK-009',
      cargoType: 'Meat',
      breachTemp: 9.5,
      severity: 'CRITICAL',
      pipelineStart: '11:55:30 AM',
      pipelineEnd: '11:55:48 AM',
      totalDuration: 1.5,
      finalOutcome: 'CONTAINED',
      timestamp: 'May 16, 11:55 AM',
    ),
    Incident(
      incidentId: 'INC-20260515-004',
      truckId: 'TRK-002',
      cargoType: 'Dairy',
      breachTemp: 8.2,
      severity: 'MEDIUM',
      pipelineStart: '08:44:10 AM',
      pipelineEnd: '08:44:29 AM',
      totalDuration: 1.9,
      finalOutcome: 'CONTAINED',
      timestamp: 'May 15, 08:44 AM',
    ),
    Incident(
      incidentId: 'INC-20260514-001',
      truckId: 'TRK-005',
      cargoType: 'Dairy',
      breachTemp: 9.1,
      severity: 'CRITICAL',
      pipelineStart: '02:20:15 PM',
      pipelineEnd: '02:20:31 PM',
      totalDuration: 1.6,
      finalOutcome: 'CONTAINED',
      timestamp: 'May 14, 02:20 PM',
    ),
    Incident(
      incidentId: 'INC-20260513-002',
      truckId: 'TRK-003',
      cargoType: 'Meat',
      breachTemp: 6.8,
      severity: 'CRITICAL',
      pipelineStart: '05:10:40 PM',
      pipelineEnd: '05:10:57 PM',
      totalDuration: 1.7,
      finalOutcome: 'CONTAINED',
      timestamp: 'May 13, 05:10 PM',
    ),
  ];
}
